blank_issues_enabled: false
contact_links:
  - name: "â“ Question"
    url: https://github.com/weyoss/redis-smq/discussions/new?category=q-a
    about: "Ask questions about usage, configuration, or best practices and get help from the community"

  - name: "ğŸ†˜ Support Request"
    url: https://github.com/weyoss/redis-smq/discussions/new?category=q-a
    about: "Need help with implementation or troubleshooting? Post your support requests here"

  - name: "ğŸ“š Documentation"
    url: https://github.com/weyoss/redis-smq/tree/master/packages/redis-smq/docs/README.md
    about: "Consult our comprehensive documentation for guides, API references, and examples before reporting issues"